services:
  mysql:
    image: mysql:latest
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:13.4
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    platform: linux/amd64
    restart: always
    ports:
      - '8080:8080'

volumes:
  mysql-data:
  postgres-data:
